version: "3.8"
services:
  keydb:
    image: eqalpha/keydb
    container_name: keydb
    ports:
      - "6379:6379"
    volumes:
      - keydb_data:/data
    environment:
      - KEYDB_DATABASES=16

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  keydb_data:
  mariadb_data:
